name: Auto Check

on:
  watch:
    types: started
  push:
  schedule:
    - cron: '0 21 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # [2.7, 3.5, 3.6, 3.7, 3.8] 目前只用到 Python3.8
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Glados Check!
      env:
        KOA_SESS: ${{ secrets.KOA_SESS }}
        KOA_SESS_SIG: ${{ secrets.KOA_SESS_SIG }}
      run: |
        python GladosAutoCheck.py


